"""Pipeline watchdog monitoring active jobs for stale states and verifying remote completion."""

import asyncio
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from app.config import settings
from database.connection import transaction, get_db_cursor
from database.models import Job, DesignStatus, LovableStatus, VercelStatus, OverallStatus
from database.repository import JobRepository
from utils.logger import logger, format_log_message
from utils.timestamps import now_iso


class WatchdogReport(BaseModel):
    """Report generated by a watchdog inspection cycle."""

    timestamp: str = Field(default_factory=now_iso)
    stale_jobs_detected: int = 0
    recovered_count: int = 0
    lovable_verified_complete: int = 0
    vercel_verified_complete: int = 0
    retried_count: int = 0
    failed_count: int = 0
    details: List[Dict[str, Any]] = Field(default_factory=list)


class PipelineWatchdog:
    """Watchdog engine that detects stalled jobs and inspects remote external state before acting."""

    def __init__(
        self,
        repository: Optional[JobRepository] = None,
        lovable_provider: Any = None,
        vercel_provider: Any = None,
        stale_timeout_seconds: Optional[float] = None,
        check_interval_seconds: Optional[float] = None,
    ):
        self.repo = repository or JobRepository()
        self.lovable_provider = lovable_provider
        self.vercel_provider = vercel_provider
        self.stale_timeout_seconds = (
            stale_timeout_seconds
            if stale_timeout_seconds is not None
            else settings.stale_job_timeout_seconds
        )
        self.check_interval = (
            check_interval_seconds
            if check_interval_seconds is not None
            else settings.watchdog_interval_seconds
        )

        self._is_running = False
        self._task: Optional[asyncio.Task] = None
        self._stop_event = asyncio.Event()

        # Telemetry
        self.runs_count = 0
        self.last_run_at: Optional[str] = None
        self.total_recovered = 0

    @property
    def is_running(self) -> bool:
        return self._is_running

    async def start(self) -> None:
        """Start the async watchdog background loop."""
        if self._is_running:
            return
        self._is_running = True
        self._stop_event.clear()
        self._task = asyncio.create_task(self._watchdog_loop(), name="pipeline_watchdog")
        logger.info(f"PipelineWatchdog started (check interval: {self.check_interval}s, timeout: {self.stale_timeout_seconds}s).")

    async def stop(self) -> None:
        """Stop the watchdog background loop."""
        if not self._is_running:
            return
        self._is_running = False
        self._stop_event.set()
        if self._task and not self._task.done():
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
        logger.info("PipelineWatchdog stopped.")

    async def _watchdog_loop(self) -> None:
        """Internal recurring loop executing watchdog checks."""
        while self._is_running and not self._stop_event.is_set():
            try:
                await self.inspect_and_recover()
                try:
                    await asyncio.wait_for(self._stop_event.wait(), timeout=self.check_interval)
                except asyncio.TimeoutError:
                    pass
            except asyncio.CancelledError:
                break
            except Exception as exc:
                logger.error(f"Error in watchdog execution cycle: {exc}", exc_info=True)
                await asyncio.sleep(self.check_interval)

    def detect_stale_jobs(self) -> List[Job]:
        """Find active in-flight jobs that have not reported progress beyond the threshold."""
        cutoff = (datetime.now(timezone.utc) - timedelta(seconds=self.stale_timeout_seconds)).isoformat()
        with get_db_cursor(self.repo.db_path) as cursor:
            cursor.execute(
                """
                SELECT * FROM jobs
                WHERE overall_status NOT IN ('COMPLETED', 'FAILED', 'PAUSED')
                  AND updated_at <= ?
                  AND (
                      design_status IN ('ANALYZING', 'SEARCHING', 'EVALUATING')
                      OR lovable_status IN ('PREPARING', 'SUBMITTING', 'GENERATING', 'VERIFYING', 'PUBLISHING', 'GITHUB_SYNCING')
                      OR vercel_status IN ('DEPLOYING', 'VERIFYING')
                  )
                ORDER BY queue_position ASC
                """,
                (cutoff,),
            )
            rows = cursor.fetchall()
            return [self.repo._row_to_job(r) for r in rows]

    async def inspect_and_recover(self) -> WatchdogReport:
        """Inspect all stale jobs, check remote service status, and recover safely without duplicating work."""
        self.runs_count += 1
        self.last_run_at = now_iso()
        report = WatchdogReport()

        stale_jobs = self.detect_stale_jobs()
        report.stale_jobs_detected = len(stale_jobs)
        if not stale_jobs:
            return report

        logger.warning(f"Watchdog detected {len(stale_jobs)} stale jobs exceeding {self.stale_timeout_seconds}s timeout.")

        for job in stale_jobs:
            action = await self._recover_single_job(job)
            if action:
                report.recovered_count += 1
                self.total_recovered += 1
                report.details.append(action)

        return report

    async def _recover_single_job(self, job: Job) -> Optional[Dict[str, Any]]:
        """Inspect external service state for a specific stale job and resolve."""
        now = now_iso()
        job_id = job.id

        # ---------------- 1. Lovable Worker In-Flight ---------------- #
        if job.lovable_status in (
            LovableStatus.PREPARING,
            LovableStatus.SUBMITTING,
            LovableStatus.GENERATING,
            LovableStatus.VERIFYING,
            LovableStatus.PUBLISHING,
            LovableStatus.GITHUB_SYNCING,
        ):
            # First: verify whether external Lovable generation legitimately completed
            remote_done = False
            published_url = job.lovable_published_url

            if self.lovable_provider and job.lovable_project_id:
                try:
                    remote_proj = await self.lovable_provider.get_project(job.lovable_project_id)
                    if remote_proj and remote_proj.published_url:
                        published_url = remote_proj.published_url
                        remote_done = True
                    elif remote_proj and remote_proj.status in ("ready", "published"):
                        remote_done = True
                except Exception as exc:
                    logger.warning(f"Watchdog: Could not query Lovable for project {job.lovable_project_id}: {exc}")

            if remote_done and published_url:
                # External operation completed! Advance state without duplicating project
                self.repo.update_lovable_status(
                    job_id=job_id,
                    status=LovableStatus.GITHUB_READY,
                    published_url=published_url,
                )
                self.repo.record_event(
                    job_id=job_id,
                    event_type="WATCHDOG_RECOVERY",
                    message=f"Watchdog confirmed external Lovable completed at {published_url}",
                    metadata={"action": "ADVANCED_TO_GITHUB_READY", "published_url": published_url},
                )
                return {
                    "job_id": job_id,
                    "action": "ADVANCED_TO_GITHUB_READY",
                    "reason": f"External Lovable generation already succeeded ({published_url})",
                }
            else:
                # External operation did not complete in time: retry safely
                if job.retry_count < settings.max_retries:
                    new_retries = job.retry_count + 1
                    with transaction(self.repo.db_path) as cursor:
                        cursor.execute(
                            """
                            UPDATE jobs
                            SET lovable_status = 'WAITING_FOR_DESIGN',
                                retry_count = ?,
                                updated_at = ?
                            WHERE id = ?
                            """,
                            (new_retries, now, job_id),
                        )
                    self.repo.record_event(
                        job_id=job_id,
                        event_type="WATCHDOG_RECOVERY",
                        message=f"Watchdog reset Lovable job to WAITING_FOR_DESIGN (retry {new_retries}/{settings.max_retries}, project preserved)",
                        metadata={"action": "RETRY_PRESERVING_PROJECT", "project_id": job.lovable_project_id},
                    )
                    return {
                        "job_id": job_id,
                        "action": "RETRY_PRESERVING_PROJECT",
                        "reason": f"Stalled in Lovable {job.lovable_status.value}. Project ID preserved for credit safety.",
                    }
                else:
                    self.repo.mark_job_failed(job_id, f"Watchdog: Lovable generation timed out after {settings.max_retries} retries", "LOVABLE")
                    return {"job_id": job_id, "action": "MARKED_FAILED", "reason": "Max retries exceeded"}

        # ---------------- 2. Vercel Worker In-Flight ---------------- #
        if job.vercel_status in (VercelStatus.DEPLOYING, VercelStatus.VERIFYING):
            remote_done = False
            deploy_url = job.vercel_deployment_url or job.vercel_url

            if self.vercel_provider and job.vercel_deployment_id:
                try:
                    dep = await self.vercel_provider.get_deployment(job.vercel_deployment_id)
                    if dep and dep.url:
                        deploy_url = dep.url
                        remote_done = True
                except Exception as exc:
                    logger.warning(f"Watchdog: Could not query Vercel for deployment {job.vercel_deployment_id}: {exc}")

            if remote_done and deploy_url:
                self.repo.update_vercel_status(job_id=job_id, status=VercelStatus.DEPLOYED, deployment_url=deploy_url)
                self.repo.update_overall_status(job_id=job_id, status=OverallStatus.COMPLETED)
                self.repo.record_event(
                    job_id=job_id,
                    event_type="WATCHDOG_RECOVERY",
                    message=f"Watchdog confirmed Vercel deployment completed at {deploy_url}",
                    metadata={"action": "ADVANCED_TO_COMPLETED", "vercel_url": deploy_url},
                )
                return {
                    "job_id": job_id,
                    "action": "ADVANCED_TO_COMPLETED",
                    "reason": f"External Vercel deployment already succeeded ({deploy_url})",
                }
            else:
                if job.retry_count < settings.max_retries:
                    new_retries = job.retry_count + 1
                    with transaction(self.repo.db_path) as cursor:
                        cursor.execute(
                            """
                            UPDATE jobs
                            SET vercel_status = 'VERCEL_QUEUED',
                                retry_count = ?,
                                updated_at = ?
                            WHERE id = ?
                            """,
                            (new_retries, now, job_id),
                        )
                    self.repo.record_event(
                        job_id=job_id,
                        event_type="WATCHDOG_RECOVERY",
                        message=f"Watchdog reset Vercel deployment to VERCEL_QUEUED (retry {new_retries}/{settings.max_retries})",
                        metadata={"action": "RETRY_VERCEL", "deployment_id": job.vercel_deployment_id},
                    )
                    return {
                        "job_id": job_id,
                        "action": "RETRY_VERCEL",
                        "reason": f"Stalled in Vercel {job.vercel_status.value}. Deployment ID preserved.",
                    }
                else:
                    self.repo.mark_job_failed(job_id, f"Watchdog: Vercel deployment timed out after {settings.max_retries} retries", "VERCEL")
                    return {"job_id": job_id, "action": "MARKED_FAILED", "reason": "Max retries exceeded"}

        # ---------------- 3. Design Worker In-Flight ---------------- #
        if job.design_status in (DesignStatus.ANALYZING, DesignStatus.SEARCHING, DesignStatus.EVALUATING):
            if job.design_reference_url and job.design_score:
                self.repo.update_design_status(job_id=job_id, status=DesignStatus.DESIGN_READY)
                return {"job_id": job_id, "action": "ADVANCED_TO_DESIGN_READY", "reason": "Design reference found"}
            else:
                # Reset to queued for fresh research
                with transaction(self.repo.db_path) as cursor:
                    cursor.execute(
                        """
                        UPDATE jobs
                        SET design_status = 'DESIGN_QUEUED',
                            updated_at = ?
                        WHERE id = ?
                        """,
                        (now, job_id),
                    )
                self.repo.record_event(
                    job_id=job_id,
                    event_type="WATCHDOG_RECOVERY",
                    message="Watchdog reset stalled Design research to DESIGN_QUEUED",
                    metadata={"action": "RESET_DESIGN"},
                )
                return {"job_id": job_id, "action": "RESET_DESIGN", "reason": "Design research timed out"}

        return None
